# Generated by Django 3.2.9 on 2021-12-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20211230_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='admin',
        ),
    ]
