# Generated by Django 3.2.9 on 2022-01-04 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0004_remove_neighborhood_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='healthcenter_contact',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='police_hotline',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='content',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='occupants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.location'),
        ),
    ]
