# Generated by Django 3.2.9 on 2022-01-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_auto_20220105_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='content',
            new_name='description',
        ),
    ]
