# Generated by Django 3.2.9 on 2022-01-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0009_auto_20220107_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
