# Generated by Django 3.2.9 on 2022-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='healthcenter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_hotline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
