# Generated by Django 3.2.9 on 2022-01-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0012_auto_20220108_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
